/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./*.js",
    "./src/**/*.{html,js,css}",
    "./index.html",
    "./script.js",
  ],
  safelist: [
    // টেক্সট কালার
    "text-gray-800",
    "text-gray-900",
    "text-white",
    "text-yellow-500",
    "text-yellow-400",
    "text-gray-600",
    "text-gray-300",
    "text-gray-400",
    // ডার্ক মোড
    "dark:text-white",
    "dark:text-yellow-400",
    "dark:text-gray-300",
    "dark:text-gray-400",
    // ব্যাকগ্রাউন্ড
    "bg-white",
    "bg-white/80",
    "bg-gray-100",
    "bg-gray-200",
    "bg-gray-300",
    "bg-gray-800",
    "bg-gray-900",
    "bg-yellow-500",
    "bg-gradient-to-br",
    "bg-gradient-to-r",
    "bg-gradient-to-tr",
    "dark:bg-gray-800",
    "dark:bg-gray-900",
    "dark:bg-gray-800/90",
    "dark:bg-gray-800/80",
    "dark:bg-black/70",
    // বর্ডার
    "border",
    "border-gray-200",
    "border-gray-300",
    "border-gray-700",
    "border-yellow-500",
    "dark:border-gray-700",
    "dark:border-gray-700/50",
    "dark:border-yellow-400/20",
    // হোভার
    "hover:text-yellow-500",
    "hover:text-yellow-400",
    "hover:bg-gray-100",
    "hover:bg-gray-700",
    "hover:bg-gray-300",
    "hover:bg-gray-400",
    "hover:bg-yellow-600",
    "hover:text-white",
    "hover:text-gray-600",
    "hover:shadow-2xl",
    "hover:shadow-lg",
    "hover:shadow-blue-400/25",
    "hover:shadow-blue-500/25",
    "hover:shadow-pink-500/25",
    "hover:border-yellow-400/30",
    "hover:scale-105",
    "hover:scale-110",
    "hover:transform",
    "dark:hover:text-yellow-400",
    "dark:hover:bg-gray-700",
    "dark:hover:bg-gray-500",
    "dark:hover:text-gray-300",
    // বাটন
    "bg-yellow-500",
    "hover:bg-yellow-600",
    "text-white",
    "hover:text-white",
    "active",
    // অন্যান্য
    "shadow-xl",
    "shadow-2xl",
    "shadow-lg",
    "shadow-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-md",
    "rounded-full",
    // মেনু ফিল্টার
    "dark:bg-gray-700",
    "text-gray-800",
    "dark:text-white",
    "border-yellow-500",
    // গ্র্যাডিয়েন্ট
    "from-yellow-400",
    "to-orange-500",
    "from-purple-500",
    "to-pink-500",
    "from-blue-400",
    "to-cyan-500",
    "from-green-400",
    "to-teal-500",
    "from-gray-900",
    "to-gray-900",
    "from-blue-500",
    "to-blue-700",
    "from-blue-600",
    "to-blue-500",
    "from-blue-50",
    "to-blue-100",
    "to-blue-200",
    "to-blue-300",
    "from-purple-400",
    "to-purple-600",
    "from-pink-600",
    "to-pink-500",
    // ডার্ক গ্র্যাডিয়েন্ট
    "dark:from-gray-900",
    "dark:via-gray-800",
    "dark:to-gray-900",
    "dark:from-gray-800",
    "dark:via-gray-900",
    "dark:to-gray-800",
    "dark:bg-gradient-to-br",
    // অ্যানিমেশন
    "animate-pulse",
    "animate-bounce",
    // ব্লার
    "blur-2xl",
    "blur-3xl",
    "backdrop-blur-sm",
    "backdrop-blur-md",
    // ড্রপ শ্যাডো
    "drop-shadow",
    "drop-shadow-lg",
    "drop-shadow-md",
    // স্কেল
    "scale-100",
    "scale-95",
    // অপাসিটি
    "opacity-0",
    "opacity-10",
    "opacity-20",
    "opacity-30",
    "opacity-100",
    // ট্রানজিশন
    "transition",
    "transition-all",
    "transition-colors",
    "transition-transform",
    "duration-200",
    "duration-300",
    "duration-500",
    "ease-in-out",
    "ease-out",
    "delay-1000",
    "delay-500",
    // গ্রিড/ফ্লেক্স
    "grid-cols-1",
    "sm:grid-cols-2",
    "md:grid-cols-2",
    "md:grid-cols-3",
    "lg:grid-cols-4",
    "flex",
    "inline-flex",
    "flex-col",
    "flex-wrap",
    "items-center",
    "justify-center",
    "justify-between",
    "gap-10",
    "gap-2",
    "gap-4",
    "gap-6",
    "mb-1",
    "mb-10",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-6",
    "mb-8",
    "mt-2",
    "mt-4",
    "mt-6",
    "mt-8",
    "p-4",
    "p-6",
    "px-2",
    "px-3",
    "px-4",
    "py-1",
    "py-2",
    "py-3",
    "py-8",
    "py-12",
    "py-16",
    "py-32",
    "max-w-2xl",
    "max-w-5xl",
    "max-w-6xl",
    "max-w-7xl",
    "max-w-md",
    "max-w-xl",
    "w-full",
    "h-10",
    "h-12",
    "h-20",
    "h-24",
    "h-28",
    "h-32",
    "h-36",
    "h-40",
    "h-8",
    "h-auto",
    "rounded-2xl",
    // অন্যান্য দরকারি ক্লাস
    "text-center",
    "font-bold",
    "font-extrabold",
    "font-medium",
    "font-semibold",
    "leading-relaxed",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-lg",
    "text-sm",
    "text-xl",
    "text-xs",
    "z-10",
    "z-50",
    "relative",
    "absolute",
    "sticky",
    "top-0",
    "top-10",
    "top-20",
    "top-3",
    "left-10",
    "left-20",
    "left-4",
    "right-10",
    "right-20",
    "bottom-10",
    "bottom-20",
    "-top-10",
    "-left-10",
    "-right-10",
    "mx-auto",
    "me-3",
    "mr-2",
    "mr-3",
    "block",
    "inline-block",
    "hidden",
    "overflow-hidden",
    "pointer-events-none",
    "visible",
    "max-h-0",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Custom colors if needed
      },
      animation: {
        fadeIn: "fadeIn 0.5s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
